#name: CI/CD Pipeline
#
#on:
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]
#
#jobs:
#  build-and-test:
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#
#      - name: Set up JDK 21
#        uses: actions/setup-java@v3
#        with:
#          java-version: '21'
#          distribution: 'temurin'
#
#      - name: Grant execute permission for gradlew
#        run: chmod +x gradlew
#
#      - name: Build with Gradle
#        run: ./gradlew build
#
#      - name: Run tests
#        run: ./gradlew test
#
#      - name: Build Docker image
#        run: docker build -t nasa-apod-app .
#
#      - name: Save Docker image
#        run: docker save nasa-apod-app > nasa-apod-app.tar
#
#      - name: Upload artifact
#        uses: actions/upload-artifact@v4
#        with:
#          name: docker-image
#          path: nasa-apod-app.tar
#
#  deploy:
#    needs: build-and-test
#    if: github.ref == 'refs/heads/main'
#    runs-on: ubuntu-latest
#    steps:
#      - uses: actions/checkout@v3
#
#      - name: Download artifact
#        uses: actions/download-artifact@v4
#        with:
#          name: docker-image
#
#      - name: Load Docker image
#        run: docker load < nasa-apod-app.tar
#
#      - name: Deploy to EC2
#        uses: appleboy/ssh-action@master
#        with:
#          host: ${{ secrets.EC2_HOST }}
#          username: ${{ secrets.EC2_USERNAME }}
#          key: ${{ secrets.EC2_SSH_KEY }}
#          script: |
#            ./deploy.sh